FROM python:3.13-slim

WORKDIR /opt/scripts

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir \
    pandas \
    requests \
    faker \
    psycopg2-binary \
    sqlalchemy

CMD ["python"]