FROM apache/airflow:3.1.8

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    dbt-core \
    dbt-postgres \
    psycopg2-binary \
    pandas \
    requests \
    faker